### ISSUE TITLE
Bring files (audiofiles, text files) into the current app

### ISSUE THREAD

**Issue by amyfou** [arizona-linguistics/colrc-v2#131]
This used to be done by running a separate static server; now we will want to find a way to bring the files into the repo from a service (maybe google drive, maybe dropbox) via an api (?)

**Comment by jivens** [comment]
First step: figure out how to use DropBox to store files, then use code to pull those files. Maybe this is a mounted volume that is shared by docker images in the docker-compose file. Maybe a seperate step in the docker-compose file or maybe part of the nginx build? This is something that ulitmately nginx will share up so that other services can use the files. nginx will serve as the static server for these files.

**Comment by waocats** [comment]
If we end up using Dropbox, we can use Dropbox's [dbxcli](https://github.com/dropbox/dbxcli) to download/extract a zipped archive of the files on build. I can also see this being particularly useful in the event that new files are uploaded using the frontend, since we can use it to add those files on-update to Dropbox as well.

**Comment by waocats** [comment]
```dockerfile
# Download and install latest version of the dbxcli binary
RUN (export DROPBOX_LATEST=\
    `curl -s https://api.github.com/repos/dropbox/dbxcli/releases/latest \
    | grep -oP '(?<="tag_name": ")v[.0-9]*'` \
    && curl -Lo /usr/local/bin/dbxcli https://github.com/dropbox/dbxcli/releases/download/$DROPBOX_LATEST/dbxcli-linux-amd64)

RUN chmod +x /usr/local/bin/dbxcli

#RUN dbxcli get ...
```
I got to about here when I realized that `dbxcli` doesn't have any way of authenticating solely using the CLI. First a command must be run unsuccessfully, and then it follows the standard OAuth2 flow (wherein you open a link in your browser and authorize `dbxcli` to access your files).

However, I saw that Dropbox's API does let you do this, but you need to create an app through the developer portal in order to get an access token for it. I tested this by doing something along the lines of this on my machine and it worked just fine.
```bash
curl -X POST https://content.dropboxapi.com/2/files/download 
--header "Authorization: Bearer <COLRC-access-token>"
--header "Dropbox-API-Arg: {\"path\": \"/file.txt\"}" -o file.txt
```
If we can find some way to store the access token more privately, I think we should be in good shape.

**Comment by jivens** [comment]
Looking into this now.. the one thing that I am confused about is that the get command only gets one file at a time. I was looking for a way to download an entire directory. I think that this can be done with curl and a shared link.. similar to 
wget --max-redirect=20 -O download.zip https://www.dropbox.com/sh/igoku2mqsjqsmx1/AAAeF57DR2ou_nZGC4JPoQKfa
This would get an entire directory and zip it. I think.. trying now.

**Comment by waocats** [comment]
From the [Dropbox docs](https://www.dropbox.com/developers/documentation/http/documentation#files-download_zip):

```bash
curl -X POST https://content.dropboxapi.com/2/files/download_zip \
    --header "Authorization: Bearer <COLRC-access-token>" \
    --header "Dropbox-API-Arg: {\"path\": \"/files\"}" -o files.zip
```

**Comment by waocats** [comment]
I was able to get it to work. I made a share link for the folder, and ran

```bash
curl -Lo test.zip <share-link>
```

**Comment by jivens** [comment]
I have been getting these messages:
unzip -l test.zip
Archive:  test.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test.zip or
        test.zip.zip, and cannot find test.zip.ZIP, period.

**Comment by waocats** [comment]
Weird... I tried running `unzip -l test.zip` and it works fine on my machine. Was this with `curl` or `wget`?

**Comment by waocats** [comment]
I actually just managed to replicate the issue by running `curl -o test.zip <link>` instead of `curl -Lo test.zip <link>`. Make sure you use the `-L` option with `curl` to follow redirects.

**Comment by jivens** [comment]
I recreated the link and then it worked with this:
`curl <link>?dl=1 -L -O -J`
The link -L follows redirects and the -O and -J preserves the name of the directory. So I get (in my case) a `colrc.zip` file with the files inside it.

**Comment by jivens** [comment]
I like that approach. I tried an approach with the public Dropbox link in the Dockerfile and that worked as well. This line is currently working:
```
RUN cd /var/www/colrc/files && \
    curl <link>?dl=1 -O -J -L && \
    zip -d colrc.zip "__MACOSX*" && \
    jar xf colrc.zip && \
    rm colrc.zip
```
Note that I don't need to use the dbxcli.

**Comment by waocats** [comment]
Mine looks pretty similar.

```dockerfile
RUN mkdir -p ${NGINX_FILE_DIR} \
    && cd ${NGINX_FILE_DIR} \
    && curl -Lo audio.zip https://www.dropbox.com/sh/m6rjdax7ikevkb7/AAAAAcI1GTysCsgcNDpj2lnka?dl=0 \ 
    && unzip audio.zip -x / \
    && rm -f audio.zip

RUN chmod 755 ${NGINX_FILE_DIR} && chmod 644 ${NGINX_FILE_DIR}/*
```

I've been having some issues getting `nginx` to serve files properly, though. I've tried messing with the config, but nothing seems to come up.

**Comment by jivens** [comment]
I am fixing this.. in order to fix it you need to alter a hasura computed field in the Data/Autdiofiles tab. This was set to compute the old node process address for serving static files. The new one has this link (for development): 
![AudioFilePathDev](https://user-images.githubusercontent.com/17900585/123493228-ac908b80-d5d0-11eb-9a8a-b5a5ef3f08cc.PNG)

**Comment by jivens** [comment]
I also fixed a problem where the Dockerfile had some bad volumes in it. I basically removed (commented out) all of the nginx volumes. This was overwriting the files directory even after putting files in it.

**Comment by waocats** [comment]
Alright, I (about a couple of minutes before that reply) published the issue branch and committed my changes. Do you want to pull and fix those real quick?

As for the zip, Dropbox seems to do something weird with it. Excluding "/" (thus `-x /`) worked for me. Saves a command :)

**Comment by jivens** [comment]
I'll check out the branch soon-ish.

**Comment by waocats** [comment]
Woohoo! We've got a good start, but here are some future tasks before we can wrap up...
- [ ] Renaming the files so we no longer get 414 errors
- [ ] Making sure all of the files are uploaded to Dropbox
- [ ] Make Dropbox downloads more secure (using the API)
- [ ] Export access permissions from Hasura
- [ ] Get file uploads working through the frontend
- [ ] Use Dropbox as a backup and sync files with production server

**Comment by jivens** [comment]
All issues resolved.
