### ISSUE TITLE
Figure out why texts table shows duplicate texts when sorted by cycle

### ISSUE THREAD

**Issue by amyfou** [arizona-linguistics/colrc-v2#149]
Look at 'coyote hunts crane and releases salmon' and 'coyote imitates magpie (bungling host)'.  There may be others.  There is only one entry in the table for each of these, but they show up on multiple pages of results iff the table is sorted by 'cycle'.

**Comment by waocats** [comment]
In [`queries.js`](https://github.com/arizona-linguistics/colrc-v2/blob/main/frontend/src/queries/queries.js):
```sql
query getTextsQuery($limit: Int, $offset: Int, $order: [texts_order_by!], $where: texts_bool_exp) { 
...
}
    texts(limit: $limit, offset: $offset, order_by: $order, where: $where) {
      id
      title
      speaker
      cycle
      ...
}
```
The reason this has unintended behavior is because when a limit and/or offset is imposed, Postgres doesn't know how to sort when the cycles are the same. Thus, the results can be a little unpredictable. I think an internal secondary sort on ID may be good, but this behavior may be replicated in other parts of the site, too. Figuring out a sitewide solution would probably be in our best interest...
